FROM node:22-alpine

WORKDIR /app
COPY package*.json .

RUN npm ci --only=production

# will change much more often than the dependencies
# keep those things that change towards the end of docker file
COPY index.js index.js

CMD ["node", "index.js"]